apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netutils-allow-privileged
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - privileged
  verbs:
  - use
