apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netutils-allow-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netutils-allow-privileged
subjects:
- kind: ServiceAccount
  name: netutils
  namespace: netutils
